apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: mharcaksacr.azurecr.io/hello-world-flux:v1.0.0 # TODO: Replace with your container registry name
        ports:
        - containerPort: 8080